provenance:
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Emma MacKenzie
    email: ...
  - author: Sophie Winterbourne
    email: ...
  website:
  date run: 2021-06-24
  riboviz-version: 2.1 | COMMIT tbc
  GEO: GSE52968
  reference: Dom34 Rescues Ribosomes in 3Â´ Untranslated Regions, Guydosh & Green 2014
  DOI: https://doi.org/10.1016/j.cell.2014.02.006
  notes: The vignette was made using the Guydosh & Green 2014 dataset.

adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: data/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: G-Sc_2014
dedup_stats: false
dedup_umis: false
dir_in: G-Sc_2014/input
dir_index: G-Sc_2014/index
dir_out: G-Sc_2014/output
dir_tpm: G-Sc_2014/tpm
do_pos_sp_nt_freq: true
extract_umis: false
feature: CDS
features_file: data/yeast_features.tsv
fq_files:
  Wt: SRR1042855.fastq.gz
  Wt_3-AT: SRR1042864.fastq.gz
group_umis: false
is_riboviz_gff: true
job_email_events: beas
job_email: null 
job_memory: 20G
job_name: riboviz
job_num_cpus: 10
job_parallel_env: sharedmem
job_runtime: 18:00:00
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv 
nextflow_work_dir: G-Sc_2014/work
num_processes: 16
orf_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa
orf_gff_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
output_pdfs: true
primary_id: Name
publish_index_tpm: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
samsort_memory: 768M
sample_sheet: null
secondary_id: null 
skip_inputs: false
stop_in_cds: false
stop_in_feature: false
trim_5p_mismatches: true
t_rna_file: data/yeast_tRNAs.tsv
umi_regexp: null
validate_only: false
