
provenance:
  authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author:
    email: ...
website:
  date run: 2020-04-28
  riboviz-version: 2.0 | COMMIT
  GEO: GSE52236
  reference: Extensive and coordinated control of allele-specific expression by both transcription and translation in Candida albicans. Genome Res 2014 Jun;24(6):963-73.
Muzzey D, Sherlock G, Weissman JS.
  DOI: https://doi.org/10.1101/gr.166322.113
  notes: >
    Candida albicans RPF dataset (2 bio reps, one with 2 technical reps)


adapters: CTGTAGGCACCATCAAT # Illumina sequencing adapter(s) to remove
aligner: hisat2 # short read aligner to use. Currently only hisat2 works
asite_disp_length_file: NULL # Table of fixed A-site positions by read length
buffer: 120 # Length of flanking region around the CDS
build_indices: TRUE # build indices for aligner? if TRUE, remake indices from fasta files
cmd_file: run_riboviz_M-Ca_2014.sh # File to log bash commands
codon_positions_file: NULL  # Codon positions in each gene
count_reads: TRUE # Scan input, temporary and output files and produce counts of reads in each FASTQ, SAM, and BAM file processed?
count_threshold: 64 # Remove genes with a read count below this threshold, when generating statistics and figures
dataset: M-Ca_2014 # Name of the dataset
dir_index: M-Ca_2014/index # directory to put built indices in
dir_in: M-Ca_2014/input # input directory
dir_logs: M-Ca_2014/logs # log files directory
dir_out: M-Ca_2014/output # output directory
dir_tmp: M-Ca_2014/tmp # tmp directory for intermediate files
do_pos_sp_nt_freq: FALSE # Do calculate position-specific nucleotide freqeuency
features_file: NULL # file of features to correlate with ORFs
fq_files: # fastq files to be processed, relative to dir_in
  WT_A: SRR1027794.fastq.gz # ribosome profiling, bio rep A techrep 1
  WT_A2: SRR1027795.fastq.gz # ribosome profiling, bio rep A techrep 2
  WT_B: SRR1027796.fastq.gz # ribosome profiling, bio rep B
is_riboviz_gff: TRUE # Does the GFF file contain 3 elements per gene - UTR5, CDS, and UTR3
is_test_run: FALSE # Is this a test run
make_bedgraph: TRUE # output bedgraph.gzs of data, in addition to h5?
max_read_length: 50 # Maximum read length in H5 output
min_read_length: 10 # Minimum read length in H5 output
num_processes: 8 # number of processes to parallelize over
orf_fasta_file: M-Ca_2014/input/CAlbi_CDS_with_120bputrs.fa # orf file to align to
orf_gff_file:  M-Ca_2014/input/CAlbi_CDS_120bpL_120bpR.gff3 # GFF2/GFF3 file for ORFs
orf_index_prefix: CAlbi_CDS_with_120bputrs # ORF index file prefix, relative to dir_index
primary_id:  Name # Primary gene IDs to access the data (YAL001C, YAL003W, etc.)
rpf: TRUE # Is the dataset an RPF or mRNA dataset?
rrna_fasta_file: M-Ca_2014/input/Calbicans_rRNA_tRNA.fa # rRNA file to avoid aligning to
rrna_index_prefix: Calbicans_rRNA_tRNA # rRNA index file prefix, relative to dir_index
secondary_id: NULL # Secondary gene IDs to access the data (COX1, EFB1, etc.)
stop_in_cds: TRUE # Are stop codons part of the CDS annotations in GFF?
t_rna_file: NULL # tRNA estimates
